### ISSUE TITLE
Off-by-one error on RowImpl.get(String columnName)

### ISSUE THREAD

**Issue by bsungur** [robert-bor/CSVeed#109]
When calling get(String) on a Row, the result is off by one column.

This seems to be due to Column in Header being 1 indexed. 
While cells in LineWithInfo is List which is 0 indexed.

**Comment by hazendaz** [comment]
@bsungur ok I cannot release this myself as I don't have permission.  I pinged @robert-bor to perform a release.  Please see ticket #113 and follow from there.  Thanks.
