### ISSUE TITLE
Add `\uFEFF ` BOM  to EncounteredSymbol with `trash = true`

### ISSUE THREAD

**Issue by TimQuist** [robert-bor/CSVeed#123]
Running into an issue where the first header column in the CSV file cannot be read when uploading a file that contains the Unicode Byte Order Mark `U+FEFF`. This could be solved by marking this symbol as trash.

Is it an idea to add this character to the `EncounteredSymbol` enum with `trash = true` value so this mark is filtered out if present?

Found thanks to @ArjanVlek

**Comment by hazendaz** [comment]
@TimQuist 

Fix has been released, note releases are occurring from my fork as I have all but release access here and didn't hear anything back after doing that back in 2019 so sticking to the fork release.  All PRs can come here or there, either way will pick them up.  I added a note here at 0.7.0 to look over there so I don't have to add notes twice and want to try to make it easy on myself given there isn't much activity here.

https://github.com/hazendaz/CSVeed/releases/tag/csveed-0.7.1

The release itself should show up in next couple hours as 0.7.1.  Thanks.
