### ISSUE TITLE
Not using CRLF as line separator for writing as per specification?

### ISSUE THREAD

**Issue by mparaz** [robert-bor/CSVeed#57]
In RowWriterImpl:
`writer.write(rowInstructions.getEndOfLine());`

which is:
`return this.symbolMapping.getFirstMappedCharacter(EncounteredSymbol.EOL_SYMBOL);`

which is only ever one character, the \r of the \r\n:
`char[] mappedCharacters = symbolToChars.get(encounteredSymbol);
return mappedCharacters == null ? 0 : mappedCharacters[0];`

As a workaround, I passed in a `Writer` that overrides `write(int)`

**Comment by manish-in-java** [comment]
:+1:

**Comment by SanderBenschop** [comment]
This should be fixed in the latest version
